import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/commons/navbar";
import Footer from "@/components/commons/footer";
import { Exo } from "next/font/google";
import { Toaster } from "sonner";
import AuthProvider from "@/provider/auth-provider";
import CartContextProvider from "@/provider/cart-provider";
import WishListContextProvider from "@/provider/wish-provider";

const exo = Exo({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
  fallback: ["system-ui", "arial"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${exo.className} antialiased`}
      >
        <AuthProvider>
          <CartContextProvider>
            <WishListContextProvider>
              <Navbar />
              {children}
              <Footer />
              <Toaster position="top-center" richColors />
            </WishListContextProvider>
          </CartContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
